/**
 * Seed data for materials table.
 *
 * PBR material definitions derived from the current Materials.ts texture sets
 * and wall-type properties. These values capture the visual identity of each
 * surface type for use in the level editor and rendering pipeline.
 */
import type { NewMaterial } from '../schema';

export const MATERIALS_SEED: NewMaterial[] = [
  // --- Wall type materials (keyed by MapCell value context) ---
  {
    id: 'stone-wall',
    name: 'Stone Wall',
    color: '#442222',
    emissive: '#000000',
    emissiveIntensity: 0,
    roughness: 0.9,
    metalness: 0.1,
    colorTexture: 'stone-color',
    normalTexture: 'stone-normal',
    roughnessTexture: 'stone-roughness',
    tileX: 1,
    tileY: 1,
  },
  {
    id: 'flesh-wall',
    name: 'Flesh Wall',
    color: '#661a1a',
    emissive: '#330808',
    emissiveIntensity: 0.3,
    roughness: 0.6,
    metalness: 0.05,
    colorTexture: 'flesh-color',
    normalTexture: 'flesh-normal',
    roughnessTexture: 'flesh-roughness',
    tileX: 1,
    tileY: 1,
  },
  {
    id: 'lava-wall',
    name: 'Lava Wall',
    color: '#1a0a00',
    emissive: '#ff4400',
    emissiveIntensity: 0.8,
    roughness: 0.8,
    metalness: 0.1,
    colorTexture: 'lava-color',
    normalTexture: 'lava-normal',
    roughnessTexture: 'lava-roughness',
    emissionTexture: 'lava-emission',
    tileX: 1,
    tileY: 1,
  },
  {
    id: 'obsidian-wall',
    name: 'Obsidian Wall',
    color: '#0a0510',
    emissive: '#1a0430',
    emissiveIntensity: 0.2,
    roughness: 0.3,
    metalness: 0.7,
    colorTexture: 'obsidian-color',
    normalTexture: 'obsidian-normal',
    roughnessTexture: 'obsidian-roughness',
    tileX: 1,
    tileY: 1,
  },

  // --- Floor materials ---
  {
    id: 'standard-floor',
    name: 'Standard Floor',
    color: '#220505',
    emissive: '#000000',
    emissiveIntensity: 0,
    roughness: 0.85,
    metalness: 0.05,
    colorTexture: 'floor-color',
    normalTexture: 'floor-normal',
    roughnessTexture: 'floor-roughness',
    tileX: 8,
    tileY: 8,
  },
  {
    id: 'lava-floor',
    name: 'Lava Floor',
    color: '#1a0a00',
    emissive: '#ff4400',
    emissiveIntensity: 1.0,
    roughness: 0.8,
    metalness: 0.1,
    colorTexture: 'lava-color',
    normalTexture: 'lava-normal',
    roughnessTexture: 'lava-roughness',
    emissionTexture: 'lava-emission',
    tileX: 2,
    tileY: 2,
  },
  {
    id: 'void-pit',
    name: 'Void Pit',
    color: '#050010',
    emissive: '#3300aa',
    emissiveIntensity: 0.6,
    roughness: 0.5,
    metalness: 0.2,
    tileX: 1,
    tileY: 1,
  },

  // --- Ceiling material ---
  {
    id: 'standard-ceiling',
    name: 'Standard Ceiling',
    color: '#1a0520',
    emissive: '#000000',
    emissiveIntensity: 0,
    roughness: 0.9,
    metalness: 0,
    colorTexture: 'ceiling-color',
    normalTexture: 'ceiling-normal',
    roughnessTexture: 'ceiling-roughness',
    tileX: 8,
    tileY: 8,
  },

  // --- Door material ---
  {
    id: 'door',
    name: 'Door',
    color: '#443322',
    emissive: '#111000',
    emissiveIntensity: 0.1,
    roughness: 0.7,
    metalness: 0.3,
    colorTexture: 'door-color',
    normalTexture: 'door-normal',
    roughnessTexture: 'door-roughness',
    metalnessTexture: 'door-metalness',
    tileX: 1,
    tileY: 1,
  },

  // --- Platform / Ramp materials ---
  {
    id: 'platform',
    name: 'Raised Platform',
    color: '#0a0510',
    emissive: '#1a0430',
    emissiveIntensity: 0.15,
    roughness: 0.35,
    metalness: 0.6,
    colorTexture: 'obsidian-color',
    normalTexture: 'obsidian-normal',
    roughnessTexture: 'obsidian-roughness',
    tileX: 1,
    tileY: 1,
  },
  {
    id: 'ramp',
    name: 'Ramp',
    color: '#442222',
    emissive: '#000000',
    emissiveIntensity: 0,
    roughness: 0.85,
    metalness: 0.1,
    colorTexture: 'stone-color',
    normalTexture: 'stone-normal',
    roughnessTexture: 'stone-roughness',
    tileX: 1,
    tileY: 1,
  },
];
